---
title: arr
headerStyle: clean
theme: dark
color: slate
hideVersion: true

layout:
  Media:
    style: row
    columns: 2
  Automation:
    style: row
    columns: 3
  Downloads:
    style: row
    columns: 2
  Management:
    style: row
    columns: 3
